//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Icon
    {
        public int id { get; set; }
        public string Icons { get; set; }
        public string Page { get; set; }
    }
}
