//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Text
    {
        public int id { get; set; }
        public string Tittle { get; set; }
        public string Title_content { get; set; }
        public string Text1 { get; set; }
        public string Page { get; set; }
        public Nullable<System.DateTime> Start_date { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
    }
}
